site_name: Lund.store
site_url: https://docs.lund.store/
repo_name: milarn/mkdocs
repo_url: https://github.com/milarn/mkdocs
theme:
  icon:
    repo: fontawesome/brands/git-alt
  name: material
  favicon: img/favicon.png
  logo: img/logo.png
  features:
    - navigation.sections
    - navigation.expand
    - navigation.path
    - toc.integrate
    - navigation.top
    - toc.follow
    - toc.integrate
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
   - scheme: default
     toggle:
       icon: material/toggle-switch-off-outline
       name: Switch to dark mode
     primary: teal
     accent: purple
   - scheme: slate
     toggle:
       icon: material/toggle-switch
       name: Switch to light mode
     primary: teal
     accent: lime

## MD_Extensions

markdown_extensions:
    - pymdownx.highlight:
        anchor_linenums: true
    - pymdownx.inlinehilite
    - pymdownx.snippets
    - admonition
    - pymdownx.arithmatex:
        generic: true
    - footnotes
    - pymdownx.details
    - pymdownx.superfences
    - pymdownx.mark
    - attr_list
    - pymdownx.emoji:
        emoji_index: !!python/name:materialx.emoji.twemoji
        emoji_generator: !!python/name:materialx.emoji.to_svg

plugins:
  - git-revision-date-localized:
      enable_creation_date: true
  - git-authors:
  - search:

extra:
  generator: false
  consent:
    title: Cookie consent
    description: >- 
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.
  analytics:
    provider: google
    property: G-TX4GRPD3L6
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/milarn/
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/Milarngg
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/martin-k-l-4a3921130/

copyright: |
 &copy; 2023 <a href="https://github.com/milarn/" target="_blank" rel="noopener">Martin K. Lund</a>