site_name: Lund.store
theme:
  name: material
  favicon: img/favicon.png
  logo: img/logo.png
  site_url: docs.lund.store
  cname: docs.lund.store
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
   - scheme: default
     toggle:
       icon: material/toggle-switch-off-outline
       name: Switch to dark mode
     primary: teal
     accent: purple
   - scheme: slate
     toggle:
       icon: material/toggle-switch
       name: Switch to light mode
     primary: teal
     accent: lime

## MD_Extensions

markdown_extensions:
    - pymdownx.highlight:
        anchor_linenums: true
    - pymdownx.inlinehilite
    - pymdownx.snippets
    - admonition
    - pymdownx.arithmatex:
        generic: true
    - footnotes
    - pymdownx.details
    - pymdownx.superfences
    - pymdownx.mark
    - attr_list
    - pymdownx.emoji:
        emoji_index: !!python/name:materialx.emoji.twemoji
        emoji_generator: !!python/name:materialx.emoji.to_svg

extra:
  generator: false
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/milarn/
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/Milarngg
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/martin-k-l-4a3921130/

copyright: |
 &copy; 2023 <a href="https://github.com/milarn/" target="_blank" rel="noopener">Martin K. Lund</a>